### ISSUE TITLE
What do the 8 points in `MCSObject.dimensions` mean, and what does the scalar `rotation` angle mean for a rolling cube?

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#124]
# 8 points of `dimensions`
The [documentation](https://github.com/NextCenturyCorporation/MCS/blob/master/python_api/API.md#dimensions--list-of-dicts) says:

> ## dimensions : list of dicts
>
> The dimensions of this object in the environment's 3D global coordinate system as a list of 8 points (dicts with "x", "y", and "z").

What do the 8 points mean in terms of the object dimensions?  Is it the case that all `MCSObject`s are assumed to be rectangular prisms and these 8 points are the vertices?

# Scalar rotation angle
I'm inspecting the step outputs in the debugger, for the scene state screenshotted here:
![image](https://user-images.githubusercontent.com/4324055/84688233-00bc5680-af0d-11ea-891d-4f7a48c7b381.png)
It looks like `position` refers to the object's geometric center:
```
(Pdb) output.object_list[0].position
{'x': 3.378843, 'y': 1.84360349, 'z': 1.60156357}
```
But I'm not sure what the `rotation` means:
```
(Pdb) output.object_list[0].rotation
0.345139176
```
I would expect the orientation to require 3 numbers to express, since the cube has no constraints on its orientation (it's not sliding on the table, for example).  Could you help me understand what `rotation` means in this case?

A second case where I'm unsure what the `rotation` means is here, where we have 2 occluder walls and 2 occluder polls:
![image](https://user-images.githubusercontent.com/4324055/84692999-c5be2100-af14-11ea-875d-df1a4a2a64a9.png)
Here (and I think throughout the whole scene), all rotation angles are reported as zero:
```
(Pdb) [o.rotation for o in output.structural_object_list]           
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
How can I inspect the incline angle of the occluder?

Thanks!

**Comment by ThomasSchellenbergNextCentury** [comment]
Each object has a rectangular prism bounding box, so the `dimensions` correspond to that bounding box.  We decided not to return more complex shape representations because it dramatically decreased performance (since even simple shapes like spheres contained hundreds of points) and no one said they were using them.

Rotation is in Euler angles in Z/X/Y order.  See the documentation here:  https://docs.unity3d.com/ScriptReference/Transform-eulerAngles.html

Each occluder wall SHOULD be returning its rotation... If it isn't, that's a bug we'll need to investigate.

**Comment by bzinberg** [comment]
Thanks @ThomasSchellenbergNextCentury!  Makes sense for the bounding box.

> Rotation is in Euler angles in Z/X/Y order.

That's what I would expect (in some Euler angle order), but that cyan cube's `MCSObject.rotation` is a single scalar.

> Each occluder wall SHOULD be returning its rotation... If it isn't, that's a bug we'll need to investigate.

Great, thanks - I'll work with @fplk to get you repro instructions.

**Comment by bzinberg** [comment]
Here are the repro instructions:

1. Load the environment [`object_permanence_goal-0800.json`](https://gist.github.com/bzinberg/0f8bc3a437ccb062b4f53124cda1b38e) into MCS.
2. `Pass` 6 times.  That should result in this image:
![image](https://user-images.githubusercontent.com/4324055/84692999-c5be2100-af14-11ea-875d-df1a4a2a64a9.png)
3. Inspect the `rotation`s in the most recent step output:
```
>>> {o.uuid: o.rotation for o in output.structural_object_list}

{'floor': 0.0,
 'occluder_pole_71435b6b-d530-411a-a949-be8e1e308a14': 0.0,
 'occluder_pole_78fa74fe-a83d-48f8-9edc-cb21d184afa4': 0.0,
 'occluder_wall_71435b6b-d530-411a-a949-be8e1e308a14': 0.0,
 'occluder_wall_78fa74fe-a83d-48f8-9edc-cb21d184afa4': 0.0,
 'wall_front': 0.0}
```

**Comment by ThomasSchellenbergNextCentury** [comment]
I believe this issue was fixed in our latest release (last week)?

**Comment by bzinberg** [comment]
I think so!
