### ISSUE TITLE
Square pixels?

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#131]
The [`camera_aspect_ratio`](https://github.com/NextCenturyCorporation/MCS/blob/d057bb4f6238de95524df119ccbb965f3c880339/python_api/API.md#camera_aspect_ratio--float-float) field is described as:

> The player camera's aspect ratio. This will remain constant for the whole scene.

Inspecting the value of this field in some examples, it looks like these two floats are the width and height in pixels of the output images (`image_list[i]`).

If that's correct, then requesting your confirmation that the simulator's camera always has a [pixel aspect ratio](https://en.wikipedia.org/wiki/Pixel_aspect_ratio) of 1 (or if not, requesting that the pixel aspect ratio be made available in the API).  The pixel aspect ratio (or equivalent information, such as the display aspect ratio) is important because it determines what the shape of the field of view has when viewed in world units -- and that allows our agent to reason about whether it should or should not be able to see an object with a given `[x, y, z]` position.

**Comment by ThomasSchellenbergNextCentury** [comment]
The [aspect ratio](https://en.wikipedia.org/wiki/Aspect_ratio_(image)) is 600:400, a.k.a. 3:2.  Yes, it's the same as the image height and width.

I don't think that we know the "pixel aspect ratio".  However, if there are other Unity camera properties that you would like to know, we can return those to you: 
https://docs.unity3d.com/ScriptReference/Camera.html

**Comment by bzinberg** [comment]
Thanks @ThomasSchellenbergNextCentury.  Since no one seems to mention this on the Unity forums, hopefully the pixel aspect ratio is always 1 in Unity.  The thing that then confused me was that this implies that the horizontal and vertical field of view angles are different, but there is only one `field_of_view`.

But -- it looks like Unity agrees with that :slightly_smiling_face: Under [`fieldOfView`](https://docs.unity3d.com/ScriptReference/Camera-fieldOfView.html) they say:
> This is the vertical field of view; horizontal Field of view varies depending on the viewport's aspect ratio, for more information see [VerticalToHorizontalFieldOfView](https://docs.unity3d.com/ScriptReference/Camera.VerticalToHorizontalFieldOfView.html).

If the above is correct then I think I have all the info I need.  Would be good to document in API.md that the field of view angle is for the vertical filed of view, and the horizontal angle can be computed from vertical FOV and the aspect ratio.
