### ISSUE TITLE
`mcs_run_in_human_input_mode` crashes on the example invocation in the readme

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#21]
From readme:

> ## Run with Human Input
> 
> To start the Unity application and enter your actions and parameters from the terminal, you can run the mcs_run_in_human_input_mode script that was installed in the package with the MCS Python Library:
> ```
> mcs_run_in_human_input_mode <mcs_unity_build_file> <mcs_config_json_file>
> ```

## To reproduce

I tried the invocation
```
$ mcs_run_in_human_input_mode /path/to/unity_app/MCS-AI2-THOR-Unity-App-v0.0.1.x86_64 \
      /path/to/MCS/python_api/scenes/ball_far.json

Traceback (most recent call last):
  File "/home/bzinberg/probcomp/mcs_virtualenv/bin/mcs_run_in_human_input_mode", line 8, in <module>
    sys.exit(main())
  File "/home/bzinberg/probcomp/mcs_virtualenv/lib/python3.6/site-packages/machine_common_sense/run_mcs_human_input.py", line 103, in main
    debug = 'terminal' if sys.argv[3] is None else True
IndexError: list index out of range
```

## Possible fix
I think at least superficially this would be fixed by either

1. changing the line
  https://github.com/NextCenturyCorporation/MCS/blob/0d44bc4b872911b43a7bf9f12d0f3c085ae53aa6/python_api/machine_common_sense/run_mcs_human_input.py#L93
  to
```python
    if len(sys.argv) < 4:
```
  and updating the readme to reflect the fact that the `debug_files` command-line argument is required, or

2. changing the line
  https://github.com/NextCenturyCorporation/MCS/blob/0d44bc4b872911b43a7bf9f12d0f3c085ae53aa6/python_api/machine_common_sense/run_mcs_human_input.py#L103
  to
```python
    debug = 'terminal' if len(sys.argv) < 4 else True
```
  and updating the [usage instructions](https://github.com/NextCenturyCorporation/MCS/blob/0d44bc4b872911b43a7bf9f12d0f3c085ae53aa6/python_api/machine_common_sense/run_mcs_human_input.py#L94) to reflect the fact that `debug_files` is optional.

**Comment by ThomasSchellenbergNextCentury** [comment]
Thanks @bzinberg , I forgot about that part.  I'll update the README and add a fix now.

**Comment by brianpippin** [comment]
Thomas, I already have a fix for this in the ticket I am working on:

debug = True
    if sys.argv[3] is not None:
        debug = sys.argv[3].lower() == 'true'

    enable_noise = False
    if sys.argv[4] is not None:
        enable_noise = sys.argv[4].lower() == 'true'
