### ISSUE TITLE
Document or eliminate metadata levels "none" and ""

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#233]
# Background

This originally showed up in https://github.com/NextCenturyCorporation/MCS/pull/231#issuecomment-773695233, where test-running that PR surfaced an unrelated error.  With @ThomasSchellenbergNextCentury's help ([Slack](https://machinecommonsense.slack.com/archives/CTR31V12M/p1612490361101700)), we determined this was likely caused by our invocation of the simulator accidentally running on medatada level `none`.

Metadata level `none` is documented [here](https://github.com/NextCenturyCorporation/MCS/tree/23470f854e1370419b62a3a71ce690b6a0784138#metadata), but when trying to determine whether empty `depth_map_list` was due to a bug in the simulator code or the TA1 code (i.e. trying to diagnose the crash in https://github.com/NextCenturyCorporation/MCS/pull/231#issuecomment-773615214), I was looking at the documentation for `depth_map_list`:

> The list of 2-dimensional numpy arrays of depth float data from the scene after the last action and physics simulation were run. This is usually a list with 1 array, except for the output from start_scene for a scene with a scripted Preview Phase. Each depth float in a 2-dimensional numpy array is a value between 0 and the camera’s far clipping plane (default 15) correspondings to the depth in simulation units at that pixel in the image.

and wasn't able to tell whether the spec allowed the field to contain an empty list under any circumstances.

# Suggested changes

These suggested clarifications aim to make it easier to diagnose bugs in both the simulator and TA1 submissions that invoke the simulator.

In the documentation of the [`metadata`](https://github.com/NextCenturyCorporation/MCS/tree/23470f854e1370419b62a3a71ce690b6a0784138#metadata) field in the controller config file:
* Document the default value.
* If the default value remains `""`, then document what metadata level `""` means.

In the documentation of [`depth_map_list`](https://github.com/NextCenturyCorporation/MCS/blob/23470f854e1370419b62a3a71ce690b6a0784138/machine_common_sense/API.md#class-machine_common_sensestep_metadatastepmetadataaction_listnone-camera_aspect_rationone-camera_clipping_planesnone-camera_field_of_view00-camera_height00-depth_map_listnone-goalnone-habituation_trialnone-head_tilt00-image_listnone-object_listnone-object_mask_listnone-poseundefined-positionnone-return_statusundefined-reward0-rotation00-step_number0-structural_object_listnone):
* Document what the field holds in metadata level `none`
* Document what the field holds in the Preview Phase case (or say that the Preview Phase case is not part of the public API yet)

In the documentation of any other field whose behavior depends on metadata level:
* Document what the field holds in metadata level `none`

**Comment by rartiss55** [comment]
Most of the documentation has been updated. Still need to update GoalMetadata docs as part of internal TA2 ticket https://nextcentury.atlassian.net/browse/MCS-622.
