### ISSUE TITLE
Changes to Classification (Choice) and Confidence

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/MCS#237]
From: TA2

Priority: Eval 4

Components: Python API (`make_step_prediction`, `end_scene`)

Blockers: Needs design (TA2) and approval (TA1)

Issues:
- The term "confidence" has a specific meaning in machine learning, which has lead to some confusion
- We may want to encourage teams to provide a confidence value rather than rely on a default value
- We may want to provide feedback (like an error message) if an incorrectly-formatted confidence value is passed
- We want the API to support both VoE and future non-binary classification tasks in a clear way

Possible Solutions:
- Rename `confidence` to `score` (or `plausibility_score`, or `continuous_score`), to mimic the terminology used in the Eval 4 Plan
- Rename `choice` to `rating` (or `plausibility_rating`, or `binary_rating`), to mimic the terminology used in the Eval 4 Plan
- Update the documentation in GoalMetadata to describe the expectations for intuitive physics versus agents as detailed in the Eval 4 Plan
- Reject function calls with incorrectly-formatted data based on the goal category

TA2 internal JIRA ticket: https://nextcentury.atlassian.net/browse/MCS-513

**Comment by deanwetherby** [comment]
https://machinecommonsense.slack.com/archives/CTR31V12M/p1615651333007600

Ben Zinberg Yesterday at 11:02 AM
Confirming that the confidence kwarg to Controller.end_scene has the meaning of 0 = sure implausible, 1 = sure plausible, 0.5 = totally uncertain (and continuous partial uncertainty in between)?  (If so, perhaps we should rename that kwarg to something like soft_choice) (edited)

**Comment by ThomasSchellenbergNextCentury** [comment]
Related to: https://github.com/NextCenturyCorporation/MCS/issues/263

**Comment by rartiss55** [comment]
Resolved in the previously linked PR + included in the 0.4.4 release.
