### ISSUE TITLE
Objects Inside a Container Should Move With the Container if Picked Up

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/MCS#238]
From: Falk

Priority: Eval 4

Components: Unity Env

Blockers: None

Objects inside a container should move with the container if it is picked up, carried, dropped, thrown, etc.

TA2 internal JIRA ticket: https://nextcentury.atlassian.net/browse/MCS-473

**Comment by kdrumm** [comment]
fixed in https://github.com/NextCenturyCorporation/MCS/pull/304
