### ISSUE TITLE
Return Performer Agent Radius and Reach in Output Step Metadata

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/MCS#239]
From: Falk, Mangannr

Priority: Backlog

Components: Python API, Unity Env

Blockers: None

Goal: Return the performer’s radius and reach so the TA1s always know their exact value, in case we change them in the future, since they’re useful for the TA1s in developing the ML models.

In Unity:
- Add two new variables (maybe called performerRadius and performerReach) to the MetadataWrapper class in the AgentManager file.
- Return the MCSController’s CapsuleCollider’s Radius in the output MetadataWrapper as the performerRadius (MCSController.generateMetadataWrapper).
- Return the MCSController’s maxVisibilityDistance (this variable sets the performer’s reach) in the output MetadataWrapper as the performerReach (MCSController.generateMetadataWrapper).

In Python:
- Add two new float properties (maybe called performer_radius and performer_reach) to the StepMetadata class, and update its documentation.
- Fill the two new properties in the MCS Controller’s wrap_output function with the radius and reach returned from Unity that you just implemented above (in the scene_event.metadata).
- Update the unit tests.

Slack links:
- https://machinecommonsense.slack.com/archives/CTR31V12M/p1605536698205900?thread_ts=1605536642.205800&cid=CTR31V12M
- https://machinecommonsense.slack.com/archives/CTR31V12M/p1605603290211400

TA2 internal JIRA ticket: https://nextcentury.atlassian.net/browse/MCS-441

**Comment by rartiss55** [comment]
Merged into development, will be included in next release (0.4.2).
