### ISSUE TITLE
JSON Serialization of StepMetadata Class

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/MCS#242]
From: Falk
- https://machinecommonsense.slack.com/archives/CTR31V12M/p1592570319405900
- https://machinecommonsense.slack.com/archives/CTR31V12M/p1612949614112600

Priority: Backlog

Components: Python API

Blockers: None

Currently you can use `str()` on a StepMetadata to convert it to JSON, but it's only valid if you delete all of the images first.

TA2 internal JIRA ticket: https://nextcentury.atlassian.net/browse/MCS-349

**Comment by deanwetherby** [comment]
Is this handled with #247 ?

**Comment by brianpippin** [comment]
That is my understanding @deanwetherby

**Comment by ThomasSchellenbergNextCentury** [comment]
Yes
