### ISSUE TITLE
Example Leads to Empty Rendering

### ISSUE THREAD

**Issue by fplk** [NextCenturyCorporation/MCS#26]
While my experiments with the human loop worked well, there is something I am missing about the Python API. When I try to run the code example I come up with code like this:

```python
from machine_common_sense import MCS

import matplotlib.pyplot as plt
import numpy as np
import time

from PIL import Image

config_json_file_path='/home/fplk/mitibm/MCS/python_api/scenes/playroom.json'
unity_app_file_path = '/home/fplk/mitibm/Downloads/AI2Thor_MCS/MCS-AI2-THOR-Unity-App-v0.0.1.x86_64'

count = 0


def select_action(output):
    global count
    if count < 3:
        count += 1
        return 'Pass', {}
    return '', {}


# Either load the config data dict from an MCS config JSON file or create your own.
# We will give you the training config JSON files and the format to make your own.
config_data = MCS.load_config_json_file(config_json_file_path)

# We will give you the Unity app file.
controller = MCS.create_controller(unity_app_file_path)

output = controller.start_scene(config_data)

test = plt.imshow(np.asarray((output.image_list[0])))
plt.show()

# Use your machine learning algorithm to select your next action based on the scene
# output (goal, actions, images, metadata, etc.) from your previous action.
action, params = select_action(output)

# Continue to select actions until your algorithm decides to stop.
while action != '':
    step_return = controller.step(action)
    plt.imshow(np.asarray((step_return.image_list[0])))
    plt.show()
    action, params = select_action(output)
    time.sleep(2)

# For interaction-based goals, your series of selected actions will be scored.
# For observation-based goals, you will pass a classification and a confidence
# to the end_scene function here.
controller.end_scene('classification', 'confidence')
```
While I see all objects in the initial data structure `config_data`, the `object_list` fields in all outputs are empty and the rendered images I show only contain backgrounds. I thus have three questions:

~a) Why is that and what can I do to render the full scene like I get in the human loop? So far I have not found the fundamental difference of the code above to what you do in `python_api/machine_common_sense/run_mcs_human_input.py`. Why does one work and the other does not?~

b) Could I be added to the AI2Thor / TA2 Slack channel to ask questions like this more dynamically? This would be great.

c) I see the depth maps as well in the data structures, but no segmentation maps. Should I segment myself (obviously more error-prone, since it involves another CV task) or is there a way to get segmentation maps directly? It seems that in the underlying AI2Thor this is accessible via `instance_segmentation_frame`, cmp. https://ai2thor.allenai.org/ithor/documentation/metadata/ - can I access the underlying system and extract this or what is the best way to obtain segmentation maps?

Thank you very much in advance.

**Comment by fplk** [comment]
Regarding (a): Oh, I see. I added `, status` in front of the `load_config_json_file` call and I see objects now. It silently failed when it got handed a tuple. Good thing I read your code :)

Would still be great to get answers regarding (b) and (c). Thanks in advance.

**Comment by ThomasSchellenbergNextCentury** [comment]
B. You should be able to add yourself to the `ta2` and `ta2-api` channels.

C. The `instance_segmentation_frame` should be available in the `object_mask_list` of the `MCS_Step_Output` object.

**Comment by fplk** [comment]
Excellent. Thank you.
