### ISSUE TITLE
Feature Request: Retrospective surprise

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#263]
# Background & Motivation

The current API for reporting frame-by-frame surprise supports only prospective surprise (i.e., the surprise reported at time _t_ is only allowed to depend on what was seen at time 1 through _t_, not after; it is not currently possible to report surprise about frame 12 based on something observed at frame 50).  In discussion on Slack [here](https://machinecommonsense.slack.com/archives/CTR31V12M/p1607371433313400?thread_ts=1607370527.311000&cid=CTR31V12M), during the PI meeting, and in the 2021-03-06 TA1/TA2 call, the idea was raised to change the API to support reporting of retrospective surprise; this feature request aims to make the proposal concretely and assess feasibility from the TA2 engineering side.

Speaking for the CORA team, our system is currently designed to focus on explaining its surprise in terms of the whole scene, so this change would help our system give meaningful explanations that are scientifically interesting to analyze.  My sense is that a similar situation is true for other teams' systems too.

Given the decision to eliminate heatmaps ([here](https://machinecommonsense.slack.com/archives/C01QF9JQHU0/p1615243350013100)), the API for reporting per-frame surprise will be changing anyway, so Eval 4 could be a great time to add support for retrospective surprise.

# Proposal

The current way of reporting per-frame surprise is the `violations_xy_list` and `heatmap_img` arguments to [`Controller.make_step_prediction`](https://github.com/NextCenturyCorporation/MCS/blob/82316198be379de59fbb2be9324b0e37a74f2d74/machine_common_sense/API.md#make_step_predictionchoice-str--none-confidence-float--none-violations_xy_list-listdictstr-float--none-heatmap_img-pilimageimage--none-internal_state-object--none).  The latter argument will be removed, as the representation of per-frame surprise is being changed.

The proposal is to, instead of reporting per-frame surprise in `make_step_prediction`, report it via a new argument to [`Controller.end_scene`](https://github.com/NextCenturyCorporation/MCS/blob/82316198be379de59fbb2be9324b0e37a74f2d74/machine_common_sense/API.md#end_scenechoice-confidence10):
> `per_frame_surprise`: Dict whose entries are:
> * key: step number (i.e., value of [`StepMetadata.step_number`](https://github.com/NextCenturyCorporation/MCS/blob/82316198be379de59fbb2be9324b0e37a74f2d74/machine_common_sense/API.md#class-machine_common_sensestep_metadatastepmetadataaction_listnone-camera_aspect_rationone-camera_clipping_planesnone-camera_field_of_view00-camera_height00-depth_map_listnone-goalnone-habituation_trialnone-head_tilt00-image_listnone-object_listnone-object_mask_listnone-poseundefined-positionnone-return_statusundefined-reward0-rotation00-step_number0-structural_object_listnone)) for the most recently seen frame
> * value: data payload indicating the AI system's surprise about that frame.

Note that this proposed change is agnostic to what the actual data type of the per-frame surprise object ends up being.

**Comment by bzinberg** [comment]
Requesting info from TA2 engineering team: How involved would the engineering work for this be?  My understanding is that the main work would be in the data ingestion pipeline, for which @brianpippin has the most context to comment.  Would love to hear your thoughts.

**Comment by deanwetherby** [comment]
Thank you for the feature request @bzinberg. We have been chatting about this topic within the TA2 team and will likely discuss during our next "in-person" video conference. The engineering work to implement this change, if agreed upon, would be relatively straight-forward. One of us will update this ticket when we know more information.

**Comment by deanwetherby** [comment]
@bzinberg We will be removing the `make_step_prediction` function from our API and instead rely on retrospective reporting with a singular `end_scene` call. This will include plausibility scoring, binary class prediction, and xy violation list per frame as well as an overall scene score and binary prediction. TA2 engineers will have to work with TA1 engineers to ensure this function call and corresponding arguments/documentation are crystal clear.

**Comment by bzinberg** [comment]
Great, thanks @deanwetherby for the update!  Happy to review the docs when ready.

**Comment by ThomasSchellenbergNextCentury** [comment]
Related to: https://github.com/NextCenturyCorporation/MCS/issues/237

**Comment by rartiss55** [comment]
Resolved in the previously linked PR + included in the 0.4.4 release.
