### ISSUE TITLE
Feature Request: Logging API, viewable in the results dashboard enabling richer & faster analysis by TA2 and TA1

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#264]
# Motivation

Each TA1 team's AI system may have diagnostic info available at runtime that makes it much faster to diagnose and understand system behavior, in terms of "what is the AI thinking."  During local development, this information can simply be printed to the terminal; however, terminal output is not currently viewable in the eval results dashboard.  This is ok, since TA1 teams can re-run scenes locally and view terminal output, but it would be very helpful to include some form of logger API whose log output can be viewed in the dashboard as that would enable both TA2 and TA1 to analyze system behavior much more quickly (and therefore to analyze far more scenes at this increased level of detail), as well as allowing more _members_ of the teams to participate in the analysis as these logs would be viewable by everyone, not just engineers who have the infrastructure set up to be able to re-run scenes locally.

# Proposal

The following sequence of proposals is inspired by the "view remote logs" feature available in many cloud computing systems.

## Option 1: Capture `stdout` and `stderr`

The most basic implementation, which would capture most of the benefit, would be to simply capture terminal output (stdout and stderr) from each run of the simulator, as a text file with some cap on the file size (TBD but hopefully reasonably high), and to ingest that data to the Eval Results dashboard so that each results row (corresponding to a specific submission's answer to a specific variant of a specific scene) links to a log output file, which will greatly help TA2 and TA1 teams come to faster and more accurate understandings of "what was the AI system thinking" that caused its behavior.

## Option 2: Add a catch-all `log(msg:str)` method to the controller

This would be similar to Option 1, but perhaps a bit cleaner in that both the simulator and AI system can be more intentional about what output to include in the logs (whereas e.g. calls into cross-language bindings often result in excess terminal output that cannot be controlled from the calling context).

## Option 3: Add logging at a few verbosity levels: `log(level:enum, msg:str)`

It is common for logging systems to expose verbosity levels such as `info`, `warning`, `error` and `verbose` so that viewers can look specifically at one type of log messages.  For example, by looking just at the `error` logs, a viewer (TA2 or TA1) can see textual descriptions of where the AI system has gotten severely confused.  Each eval results row would then include a viewable log file for each verbosity level.  Typically for best viewability, these log files are aggregated (either in the actual files or by a viewer that pulls multiple files; presumably the former is the simpler implementation strategy) into "verbosity level at most X" -- for example, the "verbosity at most `warning`" view would include both `error` log messages and `warning` log messages -- with each line of the view labelled with the verbosity level of that individual line.

**Comment by bzinberg** [comment]
Would love to hear TA2 eng team's thoughts -- how much work would this take?  Would it be feasible to implement for Eval 4?

**Comment by deanwetherby** [comment]
I like this idea but it does have some downstream impact in the evaluation pipeline, data ingestion, log storage and visualizations. I'll discuss with the team but my preference would be for option 3. We could add a logger to the mcs namespace so users of the package could provide extra information during evaluations. The pipeline would upload those logs along with the scene history and video recordings.

Something like this?
```python
import machine_common_sense as mcs
mcs.logger(mcs.logger.DEBUG, "Starting scene")
```

**Comment by bzinberg** [comment]
> Something like this?
> 
> ```python
> import machine_common_sense as mcs
> mcs.logger(mcs.logger.DEBUG, "Starting scene")
> ```

Yes, that would be great!

**Comment by deanwetherby** [comment]
The more I look into this, the more I'm realizing that It would be unusual for the TA2 MCS package to be in control of logging in this way. Normally the application (TA1 code) would set up logging via log levels, formatting, and handlers and then the package logging would just be a reflection of those settings. In the absence of application log settings, the MCS package logger should remain quiet.

https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

We can set up an internal logger that would be a reflection of application settings. And then TA1 code would have to do the following in order to enable logging.

```python
# TA1 application
import logging

logger = logging.getLogger('machine_common_sense')
# logger.setLevel()
# logger.setFormatter()
# logger.addHandler(fileHandler)

logger.info("log something")
```

The log files/ would include your own log statements plus any corresponding logs from MCS. Our code would somehow need to know the location of those log files to upload during an evaluation.

**Comment by bzinberg** [comment]
Agree that log viewing is not really a feature of the simulator, it's a property of the execution environment in which the evals are run + the dashboard in which results are viewed.  Capturing output under the name `"machine_common_sense"` in the Python standard library's logging utility (which already supports severity levels as described above) sounds great.

Perhaps the eval execution environment could include preamble code that attaches a custom handler to the `"machine_common_sense"` log, which I think would eliminate the need for the caller to save to a specific file (and possibly mess up doing so, etc.).

**Comment by deanwetherby** [comment]
We could add an evaluation file handler to the mcs package. Enabling that would give us control of the file location and be able to upload it to the UI after a scene is run. Is what you meant by your second paragraph? 

```python
import logging
import machine_common_sense as mcs

logger = logging.getLogger('machine_common_sense')
# set up terminal streaming
stream_handler = logging.StreamHandler()
stream_handler.setLevel(logging.INFO)
logger.addHandler(stream_handler)

# evaluation file logging
file_handler = mcs.get_file_handler(level=logging.INFO)
logger.addHandler(file_handler)

# log to terminal and mcs file
logger.info("hello world")
```

**Comment by ThomasSchellenbergNextCentury** [comment]
Issue Status:

Done:
- Logging

To Do:
- Configuration
- Evaluation
- Uploading
- Visualization

**Comment by rartiss55** [comment]
Should be done on the Python API side. Need to do additional implementation so that we can view the logs in the UI.
Internal TA2 JIRA tickets here:
https://nextcentury.atlassian.net/browse/MCS-886
https://nextcentury.atlassian.net/browse/MCS-887

**Comment by rartiss55** [comment]
Log files are now available in the UI in the individual scene analysis view, in the links section.

**Comment by bzinberg** [comment]
Thanks, all!  This is really helpful for Cora team (and hopefully the other TA1s), as it allows more people on our team to deep-dive into the results, who wouldn't otherwise have the time or programming expertise to give much input.
