### ISSUE TITLE
Add ffmpeg as requirement

### ISSUE THREAD

**Issue by cedorman** [NextCenturyCorporation/MCS#279]
Currently we use ffmpeg as an external program in recorder.py.

`            os.system(
                f'ffmpeg -loglevel quiet -i temp.mp4'
                f' -vcodec libx264 -vf format=yuv420p {self._path}')
`
It would be better to use a python library and call it internally or at least check for it's existence

**Comment by deanwetherby** [comment]
Do you know of a python package that does h264 video encoding? I tried numerous FOURCC codes with opencv-python but never got it to work. I think the best we can do is fail-fast with an ffmpeg check.
