### ISSUE TITLE
Gracefully handle case when no mp4 during evaluation

### ISSUE THREAD

**Issue by cedorman** [NextCenturyCorporation/MCS#280]
Sometimes (like when performers don't produce heatmaps), there is an empty mp4 file created, since no frames get added to it.  The current code simply deletes this file, but then the s3 copying process fails.   If, instead, ffmpeg gets called on the empty file, it fails and the mp4 file gets deleted (it gets copied to tmp.mp4 and then discarded).  And then the s3 copying process fails again because there is no mp4 file.  

We should gracefully handle the cases where the mp4 file is either non-existent, doesn't have any frames, ffmpeg failed for whatever reason, report an error and then continue.

**Comment by deanwetherby** [comment]
Heatmaps are no longer a reported by TA performers. Metadata levels used for evaluation ensure the creation of the visual, segmentation, and depth videos.
