### ISSUE TITLE
Re-render the videos in `machine_common_sense/scenes/videos/` at the simulator's frame rate

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#314]
Following https://github.com/NextCenturyCorporation/MCS/pull/308, it would be helpful if the rendered examples in `machine_common_sense/scenes/videos/` used the true frame rate.  These videos are important because they are often the basis of TA1/TA2 discussion and revisions of the task design.

**Comment by ThomasSchellenbergNextCentury** [comment]
I think everything there except for the old playroom GIF/video use the correct frame rate (20 FPS), but I need to redo some of those to use the new occluder rotation speed anyway, so I'll double-check.

**Comment by bzinberg** [comment]
Great, thanks @ThomasSchellenbergNextCentury!
