### ISSUE TITLE
Use the simulator's frame rate for video rendering in the results ingestion pipeline

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#315]
Following https://github.com/NextCenturyCorporation/MCS/pull/308, it would help a lot for the results analysis UI if the rendered videos used the true frame rate.

**Comment by ThomasSchellenbergNextCentury** [comment]
@bzinberg What specific difference are you expecting? I thought that they're already using the correct frame rate (20 FPS), but @deanwetherby and @brianpippin can correct me if I'm wrong.

For example, this gravity support scene, which lasts for 20 steps, has a 3 second video: http://23.20.216.233:3000/analysis?eval=Evaluation%203.5%20Results&category_type=gravity%20support&test_num=18&scene=1

**Comment by bzinberg** [comment]
If they're already using the right frame rate then great!  I didn't know whether this was happening, and https://github.com/NextCenturyCorporation/MCS/pull/308#discussion_r615948943 mentions showing the framerate number in the UI, but want to also make sure the videos actually use the frame rate (presumably another place in the codebase to touch).  And of course, that any hard-coding of the 20FPS number in the analysis pipeline be adjusted to pull from the appropriate config.

It's all stuff that might already be tracked, but I just hadn't seen any issues about it.  Thanks @ThomasSchellenbergNextCentury for following up.

**Comment by ThomasSchellenbergNextCentury** [comment]
Thanks for keeping us honest Ben. Our ingest software is now updated with https://github.com/NextCenturyCorporation/mcs-ingest/pull/12
