### ISSUE TITLE
Agent Eval4 Masks

### ISSUE THREAD

**Issue by bainro** [NextCenturyCorporation/MCS#336]
Using versions 0.4.1.1 & 0.4.2 are producing odd oracle masks for the instrumental walls for at least scene agent_instrumental_action_training_4000_01.json. 

![image](https://user-images.githubusercontent.com/31903812/118271225-d99c3b00-b475-11eb-9748-e171d7ac7309.png)

**Comment by ThomasSchellenbergNextCentury** [comment]
Thanks for reporting this. Are you just letting us know, or is this actively detrimental to your work?

**Comment by bainro** [comment]
This is actively detrimental. We're trying to create mask labels to train a segmentation neural network.

**Comment by ThomasSchellenbergNextCentury** [comment]
@bainro Sorry for the delay. We've just released version 0.4.3 which should fix this issue. Please let us know if you encounter any problems with the release.
