### ISSUE TITLE
Feature Request: 2D to 3D Conversion Matrices

### ISSUE THREAD

**Issue by zshureih** [NextCenturyCorporation/MCS#384]
### Background And Motivation

Our team is currently facing an issue where we are unable to match object mask data to object metadata. 

More robustly, at the Oracle level, the step metadata object contains a ground truth object mask image, as well as lists of structural and non-structural objects, with each object's metadata in 3d world coordinates. Currently there are no built in means to relate an object appearing in the mask image to it's corresponding metadata in the object lists. Teams can attempt to compute projection matrices that translate objects in the masks to 3d world coordinates and perform matching operations on these translated representations, but this injects one more point of failure into perception systems. 

### Solutions

Issue #240 presents one solution to this problem, a color map in StepMetadata that contains object ID string keys and color pixel array values, matching objects to their 2d and 3d representations. This is the most straightforward solution, and is preferred for our teams training needs. We suspect other teams would benefit from this information as well.

Another solution would involve giving teams direct access to the Unity computed translation matrices. Teams could transform 3d object representations into 2d image coordinates with the [Camera.worldToCameraMatrix](https://docs.unity3d.com/ScriptReference/Camera-worldToCameraMatrix.html) object, or transform 2d map image coordinates into 3d object representations with [Camera.cameraToWorldMatrix](https://docs.unity3d.com/ScriptReference/Camera-cameraToWorldMatrix.html).

With the latter solution, `StepMetadata.worldToCameraMatrix` and `StepMetadata.cameraToWorldMatrix` would contain 4x4  matrices in the OpenGL convention. The OpenGL and Unity conventions have one simple distinction: 

> Note that camera space matches OpenGL convention: camera's forward is the negative Z axis. This is different from Unity's convention, where forward is the positive Z axis.

This would either need to me made apparent to teams, or the TA2 team would have to convert the matrices into the Unity convention.

**Comment by ThomasSchellenbergNextCentury** [comment]
Thanks for the post @zshureih . Currently, while running with oracle metadata, our API returns a `color` property in each object's metadata containing the RGB values used for that object in the object masks:
https://github.com/NextCenturyCorporation/MCS/blob/master/machine_common_sense/API.md#objectmetadata

Issue https://github.com/NextCenturyCorporation/MCS/issues/240 doesn't add any new information, it just moves the existing information from the object's metadata up to the step's metadata (as requested by the CORA team).

Would you be able to use the `color` property for the moment? Or am I misunderstanding your request?

**Comment by zshureih** [comment]
We would be able to use color for the moment, yes. 

Thank you Thomas! I guess I made a false assumption about the color property here, relating it to the rgb image rather than the object masks.
