### ISSUE TITLE
EndHabitutation step

### ISSUE THREAD

**Issue by dcharrezt** [NextCenturyCorporation/MCS#405]
Hello,

I have tested the validation example provided for the interactive reorientation task, but after taking the EndHabituation with its predetermined params at step 501 I get a None output, am using the step incorrectly?

Tried on MCS 4.4
Metadata levels oracle, level2, level1

```python
import machine_common_sense as mcs

controller = mcs.create_controller(config_file_path='mcs_config.ini')

scene_data, status = mcs.load_scene_json_file('eval_4_reor_validation_01.json')

output = controller.start_scene(scene_data)

action = "Pass"
for i in range(500):
    output = controller.step(action)

action = output.action_list[0]
output = controller.step(action)

print("Output ", output) # None <--------------

action = "Pass"
for i in range(48):
    output = controller.step(action)

action = output.action_list[0]
output = controller.step(action)

controller.end_scene()

```

**Comment by ThomasSchellenbergNextCentury** [comment]
Hi @dcharrezt ,

Good question! And thank you for providing a code sample. 

The short answer is: the `action_list` returns a tuple containing an action string and a parameters dictionary. You have to pass these as separate arguments into the `step()` function.

```python
action, params = output.action_list[0]
output = controller.step(action, **params)
```

For future reference, our new [logging support](https://nextcenturycorporation.github.io/MCS/install.html#logging) could be very helpful in your development. I added the following at the top of your original code sample:

```python
mcs.LoggingConfig.init_logging(mcs.LoggingConfig.get_dev_logging_config())
```

And it showed me a bunch of debug output in the terminal, including this error message, which helped me identify your issue:

```
The given action '('EndHabituation', {'xPosition': 0.0, 'zPosition': 0.0, 'yRotation': -120.0})' with parameters '{}' isn't in the action_list. Ignoring your action. Please call controller.step() with an action in the action_list. Possible actions at step 500:
    ('EndHabituation', {'xPosition': 0.0, 'zPosition': 0.0, 'yRotation': -120.0})
```

I hope this information is helpful for you!

Thanks,

Thomas

**Comment by dcharrezt** [comment]
Thanks a lot, Thomas!
