### ISSUE TITLE
Metallic Materials Look Weird

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/MCS#406]
Affects Version 0.4.4

Metallic materials look weird when running scenes via the Python interface, as opposed to how they've looked in the past, or how they look in the Unity Editor with the current version.

In the Unity Editor:

![weird_material_issue_in_unity_editor](https://user-images.githubusercontent.com/10994382/133449274-a3eb38ba-f847-4e76-81f1-c06c48672446.png)

With the Python interface:

![weird_material_issue_run_with_python](https://user-images.githubusercontent.com/10994382/133449295-9c9db84a-b212-4f63-8f94-50ab0b6b8e0c.png)

**Comment by JuanRMarquez-Ortiz** [comment]
https://user-images.githubusercontent.com/77698548/133654751-340a8254-2bd0-4cc6-b872-beaee5e162ad.mp4

**Comment by JuanRMarquez-Ortiz** [comment]
https://github.com/NextCenturyCorporation/ai2thor/tree/bugfix/406-Metallic_Materials_Look_Weird

**Comment by JuanRMarquez-Ortiz** [comment]
Have a possible solution in place in branch: 
https://github.com/NextCenturyCorporation/ai2thor/tree/bugfix/406-Metallic_Materials_Look_Weird

Thomas seems to think it looks fine, though not exact to the original. Waiting on @deanwetherby 's input. 
![image](https://user-images.githubusercontent.com/77698548/133954561-776e9d37-74c8-49da-a9d6-94bf04d6b1d5.png)
