### ISSUE TITLE
[Urgent] How to associate segmentations with object list?

### ISSUE THREAD

**Issue by fplk** [NextCenturyCorporation/MCS#50]
It is not clear to me how to associate segmentations in `output.object_mask_list` with actual objects from my scenegraph JSON or with objects inside `output.object_list`.
a) Could you let me know how to find out which object a segmentation belongs to?
b) I noticed that when I use a scenegraph I have generated myself like the one attached (rename to .json - Github forced me to name it .txt) my `output.object_list` will be empty. Why is that?
[video_00001.txt](https://github.com/NextCenturyCorporation/MCS/files/4494037/video_00001.txt)

Thank you in advance.

**Comment by ThomasSchellenbergNextCentury** [comment]
For A, each `MCS_Object` has a [color](https://github.com/NextCenturyCorporation/MCS/blob/latest/python_api/API.md#color--dict) property that matches the color used in the output's `object_mask_list`.

**Comment by fplk** [comment]
Thank you very much. Oh, I tried that, but the values I looked at were not in the MCS_Object colors - seems like the values I tried were the walls then - stupid me :)

Still leaves question b, though - why is my object list empty for my own scene files. Because with that I still cannot associate them.

**Comment by fplk** [comment]
Essentially, my file just has a generic header and then a few objects with 50 entries in shows for the individual key frames.

Like this:
```
{"ceilingMaterial": "AI2-THOR/Materials/Walls/DrywallOrange",
"floorMaterial": "AI2-THOR/Materials/Walls/RedDrywall",
"wallMaterial": "AI2-THOR/Materials/Walls/DrywallBeige",
"performerStart": {"position": {"z": -4}},
"goal": {"action_list": [["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"], ["Pass"]]},
"objects": [
{"id": "block1", "type": "cube", "mass": 1.54, "materialFile": "AI2-THOR/Materials/Wood/LightWoodCounters4", "shows": [...]}
...
]}
```
No apparent reason to me why the `object_list` should be empty with this.

**Comment by fplk** [comment]
I think I fixed (b) - it seems that when a materialFile is defined you also expect `salientMaterials` and(?) `pickupable`. If I define all three of them I see an object_list, but my objects now fly wildly through the scene. By setting kinematic as well, we get back to sane scenes. Thanks so much for your great help - now adding the association and then I can close this issue.

**Comment by ThomasSchellenbergNextCentury** [comment]
Hey Falk, sorry for the delay, I was investigating your issue B and got pulled into a meeting.  I'm glad you found a solution to it.  To add a little more background: an object only appears in the list if you set a specific config attribute on it like `"physics": true`, `"moveable": true`, or `"pickupable": true`.  As you already saw, that will enable physics and collision detection on the object, so it will fly around wildly if it interpenetrates another object unless you also set `"kinematic": true` on the object.  We'll try to make this configuration procedure a little easier and better documented in the future.  Sorry again for the wait and that you had to be our guinea pig.
